name:         'eonx-com/actions-cloudformation'
description:  'CloudFormation template build/deployment action'
author:       'Damian Sloane <damian.sloane@eonx.com>'

inputs:
  action:
    description: 'CloudFormation action to perform (e.g. "template_build")'
    required: true
  environment_name:
    description: 'The name of the environment for use in templates (e.g. "dev", "uat", "prod")'
    required: true
  environment_path:
    description: 'The base path under which the configuration files are located'
    required: true
  template_path:
    description: 'Path to CloudFormation template files in repository'
    required: true
  output_filename:
    description: 'The compiled templates output filename'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.action }}
    - ${{ inputs.environment_name }}
    - ${{ inputs.environment_path }}
    - ${{ inputs.template_path }}
    - ${{ inputs.output_filename }}